# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.60.1"

default_platform :ios

platform :ios do
	desc "Deploying screenshots"
	lane :buildscreenshots do
		snapshot
		sh "../_helper-scripts/_screenshot-builder.sh"
	end

	desc "Deploying screenshots"
	lane :processscreenshots do
		sh "../_helper-scripts/_screenshot-builder.sh"
	end
	
end