# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
   "iPhone 8 Plus",
   "iPad Pro (12.9-inch) (2nd generation)",
   "iPhone X"
 ])

languages([
	"nl-NL",
	"de-DE",
	"en-GB",
	"es-ES",
	"fr-CA",
	"fr-FR",
	"ja-JA",
	"nl-BE",
	"nl-NL",
	"sv-SV",
	"zh-Hans",
	"zh-Hant"
])

output_directory "./_helper-scripts/_screenshot-builder/_tmp_screenshots/"
workspace 'Neodius.xcworkspace'
scheme 'Neodius'

clear_previous_screenshots true