# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
   "iPhone 8 Plus",
   "iPad Pro (12.9-inch) (2nd generation)",
   "iPhone X"
 ])

languages([
	"nb"
	"nl"
	"de",
	"en",
	"es",
	"fr-CA",
	"fr",
	"ja-JA",
	"nl-BE",
	"nl",
	"sv",
	"zh-Hans",
	"zh-Hant"
	
])

output_directory "./_helper-scripts/_screenshot-builder/_tmp_screenshots/"
workspace 'Neodius.xcworkspace'
scheme 'Neodius'

clear_previous_screenshots false
clean true
concurrent_simulators false
skip_open_summary true